swagger: "2.0"
info:
  description: "An API to register user."
  version: "1.0.0"
  title: "listUser"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteaam@thbs.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "3.215.167.185:8181"
basePath: "/tdg/api/v1"
paths:
 
  
  /userlist:
    get:
      description: "displays list of users"
      summary: "List of all users"
      produces:
        - "application/json"
        - "application/xml"
      responses:
        200:
          description: "Successful"
          
definitions: 
  User:
    properties:
      name:
        type: string
        example: deepika
      email_id:
        type: string
        example: deepika@gmail.com
    
  
      
        
            
          
       
             